apiVersion: v1
kind: Service
metadata:
  name: spring-stack-project
spec:
  selector:
    app: spring-stack-project
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 3000
  type: LoadBalancer
